name = "ControlledSMC"
uuid = "af2ad9dd-f33b-4db6-b90a-e0a5ad30adf0"
authors = ["Kyurae Kim <kyrkim@seas.upenn.edu> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
